version: 2
project_name: contexture
env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  - id: contexture
    main: ./cmd/contexture
    binary: contexture
    ldflags:
      - -s -w
      - -X github.com/contextureai/contexture/internal/version.Version={{.Version}}
      - -X github.com/contextureai/contexture/internal/version.Commit={{.Commit}}
      - -X github.com/contextureai/contexture/internal/version.BuildDate={{.Date}}
      - -X github.com/contextureai/contexture/internal/version.BuildBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - id: contexture
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - README.md
      - LICENSE
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "📚 Documentation"
      regexp: '^.*?docs?(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "🏗️ Build & CI"
      regexp: '^.*?(build|ci)(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "♻️ Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "🧪 Tests"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: "Other Changes"
      order: 999
release:
  github:
    owner: contextureai
    name: contexture
  discussion_category_name: General
  prerelease: auto
  mode: replace
  skip_upload: false
  make_latest: auto
  header: |
    ## Contexture {{ .Tag }}

    Thanks for using Contexture! This release includes the following changes:

  footer: |
    ## Installation

    ### Download Binaries
    Download the appropriate binary for your platform from the assets below.

    ### Using Go
    ```bash
    go install github.com/contextureai/contexture/cmd/contexture@{{ .Tag }}
    ```

    ### Verify Installation
    ```bash
    contexture --version
    ```

    ---
    **Full Changelog**: https://github.com/contextureai/contexture/compare/{{ .PreviousTag }}...{{ .Tag }}
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"