name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  discussions: write

env:
  GO_VERSION: "1.25"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download Go modules
        run: make deps

      - name: Run tests
        run: make test

      - name: Run integration tests
        run: make docker-integration

      - name: Run e2e tests
        run: make docker-e2e

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts for debugging
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: goreleaser-debug
          path: |
            dist/
            .goreleaser.yaml